# Generated by Django 6.0.2 on 2026-02-15 05:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SELFWEALTH", "SelfWealth"),
                            ("GENERIC", "Generic CSV"),
                        ],
                        max_length=20,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("column_mapping", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("ASX", "ASX"),
                            ("NYSE", "NYSE"),
                            ("NASDAQ", "NASDAQ"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("AUD", "AUD"), ("USD", "USD")], max_length=3
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("SHARE", "Share"), ("ETF", "ETF")],
                        default="SHARE",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "securities",
                "ordering": ["ticker"],
            },
        ),
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acquisition_date", models.DateField()),
                (
                    "original_quantity",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                (
                    "remaining_quantity",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                (
                    "cost_per_unit_aud",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "total_cost_base_aud",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                ("is_fully_matched", models.BooleanField(default=False)),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcels",
                        to="tracker.security",
                    ),
                ),
            ],
            options={
                "ordering": ["acquisition_date"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=18)),
                ("unit_price", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "brokerage",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("total_value", models.DecimalField(decimal_places=6, max_digits=18)),
                ("currency", models.CharField(default="AUD", max_length=3)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1"), max_digits=18
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "import_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="tracker.importrecord",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="tracker.security",
                    ),
                ),
            ],
            options={
                "ordering": ["-trade_date"],
            },
        ),
        migrations.CreateModel(
            name="ParcelMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matched_quantity",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                ("cost_base_aud", models.DecimalField(decimal_places=6, max_digits=18)),
                ("proceeds_aud", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "capital_gain_loss",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                ("holding_period_days", models.IntegerField()),
                ("cgt_discount_eligible", models.BooleanField(default=False)),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_capital_gain",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tracker.parcel",
                    ),
                ),
                (
                    "sell_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcel_matches",
                        to="tracker.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["parcel__acquisition_date"],
            },
        ),
        migrations.AddField(
            model_name="parcel",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcel",
                to="tracker.transaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=(
                    "trade_date",
                    "security",
                    "transaction_type",
                    "quantity",
                    "unit_price",
                ),
                name="unique_transaction",
            ),
        ),
    ]
